apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversions-deployment
spec:
  selector:
    matchLabels:
      app: conversions
  replicas: 4 # tells deployment to run 4 pods matching the template
  template:
    metadata:
      labels:
        app: conversions
    spec:
      containers:
      - name: conversions
        image: ghcr.io/nicc777/java-conversions-app::v1.1.1
        ports:
        - containerPort: 8888
        livenessProbe:
          httpGet:
            path: /conversions/v1/liveness
            port: 8888
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /conversions/v1/readiness
            port: 8888
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: conversions-service
spec:
  type: NodePort
  selector:
    app: conversions
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conversions-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /conversions/v1
        pathType: Prefix
        backend:
          service:
            name: conversions-service
            port:
              number: 9080