apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversions-deployment-v2
spec:
  selector:
    matchLabels:
      app: conversions-v2
  replicas: 2
  template:
    metadata:
      labels:
        app: conversions-v2
    spec:
      containers:
      - name: conversions-v2
        image: ghcr.io/nicc777/java-conversions-app@sha256:v2.0.0
        ports:
        - containerPort: 8888
        livenessProbe:
          httpGet:
            path: /conversions/v2/liveness
            port: 8888
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /conversions/v2/readiness
            port: 8888
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: conversions-service-v2
spec:
  type: NodePort
  selector:
    app: conversions-v2
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conversions-ingress-v2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /conversions/v2
        pathType: Prefix
        backend:
          service:
            name: conversions-service-v2
            port:
              number: 9080