apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment-v2
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-v2
  replicas: {{ .Values.replica_count }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-v2
    spec:
      containers:
      - name: {{ .Release.Name }}-v2
        image: {{ printf "ghcr.io/nicc777/java-conversions-app:%s" .Values.application_container_version }}
        ports:
        - containerPort: {{ .Values.application_port }}
        livenessProbe:
          httpGet:
            path: /conversions/v2/liveness
            port: {{ .Values.application_port }}
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /conversions/v2/readiness
            port: {{ .Values.application_port }}
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-v2
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-v2
  ports:
    - protocol: TCP
      port: {{ .Values.ingres_service_port }}
      targetPort: {{ .Values.application_port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-v2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /conversions/v2
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service-v2
            port:
              number: {{ .Values.ingres_service_port }}